server:
  port: 8080
spring:
  application:
    name: cloud-simple-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    #register-with-eureka: false

zuul:
  routes:
    ui:
      sensitiveHeaders:
      path: /ui/**
      serviceId: cloud-simple-ui
      stripPrefix: true
    api:
      sensitiveHeaders:
      path: /api/**
      serviceId: cloud-simple-service
      stripPrefix: true